### ISSUE TITLE
EasyMDE and Trix Editor vanishing with Livewire Validation

### ISSUE THREAD

**Issue by Xinecraft** [blade-ui-kit/blade-ui-kit#80]
Hi there,
I am trying to add live validation on a form and whenever any part of the form changes the EasyMDE editor just become normal textarea. 
Am I missing something which I can't find in docs?

Reference:
https://i.imgur.com/0RYUtT6.gif

**Comment by RomainMazB** [comment]
Hi,
You're not missing anything.

The problem comes from the fact Livewire re-render the Dom and the javascript isn't applied anymore to the regenerated Dom.

I've faced the problem. We need to wrap the trix-editor tag into a div with the wire:ignore attributes.

Same truck will fix easyMDE.

will PR on it probably today.

**Comment by xewl** [comment]
+1 - Also, the trix editor doesn't even seem to take wire:model into initial consideration, or.. updates 1 character behind.

**Comment by kurucu** [comment]
Hi @Xinecraft,
You might want to check out my [SO answer](https://stackoverflow.com/a/61796249/278149), which deals with exactly this.
I hope that helps.
It might also kick-start @RomainMazB's PR.

**Comment by martin-ro** [comment]
Wrap the component in `<div wire:ignore> ... </div>`
See [Livewire docs](https://laravel-livewire.com/docs/2.x/reference)

**Comment by alexmanase** [comment]
@driesvints I can create a PR to fix this issue. Is it worth it?

**Comment by driesvints** [comment]
@alexmanase yes I believe so. Would appreciate it!

**Comment by driesvints** [comment]
This should be fixed now!
